In [1]:
# pandas is sql table form datastructure
import pandas as pd
# numpy is a multidimentional array
import numpy as np

# 1. Object creation
# creating series
series = pd.Series([1,3,5,np.nan,6,8])
print(series)

# creating datetime index using dataframe
dates = pd.date_range('20130101',periods=6)
print(dates)

print(np.random.randn(6,4))
# creating data frame
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df["E"] = "Hi"
# 2. Viewing data

# viewing top 5 records
print(df.head(5))

# viewing bottom 5 records
print(df.tail(5))

# display index
print(df.index)

# display the columns
print(df.columns)

# display all column values return a multi dimensional array
print(df.values)

# get the statistical summary of all columns
print(df.describe(include='all'))

# transpose the data
print(df.T)

# sorting by axis
print(df)
print(df.sort_index(axis=1, ascending=False))
print(df.sort_index(axis=0, ascending=False))

# sort by values
print(df.sort_values(by='B'))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
[[-1.1214831   1.63637792 -0.04567465 -0.72819674]
 [ 0.2210317  -1.06221597  0.65432189  0.41140676]
 [-0.54837173  0.14458699 -0.52132872  0.7882769 ]
 [-1.19641864 -1.27945044  0.61590722 -0.31039479]
 [-0.73365205 -0.32003508 -2.1788717   0.53851572]
 [ 0.32245788 -0.73271277 -1.91287083  0.8721402 ]]
                   A         B         C         D   E
2013-01-01  0.980036 -0.480093 -0.423919 -0.194207  Hi
2013-01-02 -0.093119  0.449870  0.273013 -1.642527  Hi
2013-01-03  1.864458  1.903771  0.613987 -0.848750  Hi
2013-01-04 -2.252972 -0.938845  0.598472 -0.649513  Hi
2013-01-05 -0.383580  1.274588 -0.986375 -0.696333  Hi
                   A         B         C         D   E
2013-01-02 -0.093119  0.449870  0.273013 -1.642527  Hi
2013-01-03  1.864458 